sudo: required
services:
  - docker

script:
  - docker build -t $IMAGE .
  - docker run -it -p 5000:5000 -e PORT=5000 -e SECRET_KEY="sup" -e DATABASE_URL="sqlite:///test.db" $IMAGE /bin/bash -c "py.test"

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD quay.io;
      docker push $IMAGE;
    fi

env:
  global:
    - IMAGE=quay.io/thedataincubator/logger:$TRAVIS_COMMIT
